apiKey: XXXXXX
licenseKey: XXXXXX
region: US
log:
  level: warn
  fileName: trace.log
events:
  enabled: true
  accountId: 12345
  eventType: MyEntityTagSync
provider:
  type: servicenow
  useLastUpdate: true
  apiUrl: https://my-service-now.service-now.com
  apiUser: admin
  pageSize: 100
mappings:
- extEntityQuery:
    type: cmdb_ci_email_server
    query: "sys_updated_on>javascript:gs.dateGenerate('${lastUpdateDate}','${lastUpdateTime}')^operational_status!=2"
    serverTimezone: America/Los_Angeles
  entityQuery:
    type:
    - APPLICATION
    domain:
    - APM
    accountId: 1
  match:
    extEntityKey: name
    operator: equal-ignore-case
    entityKey: testCmdb
  mapping:
    sys_class_name: SNOW_CI_CLASS
    sys_id: SNOW_CMDB_CI
    environment: SNOW_ENVIRONMENT
    sys_domain.value: SNOW_SYS_DOMAIN
